name: "juvapay"
description: "JuvaPay - A Social Services App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2 
  supabase_flutter: ^2.6.0 
  
  image_picker: ^1.0.4  
  image_cropper: ^8.0.2
  dotted_border: ^2.1.0
  url_launcher: ^6.3.0
  lottie: ^2.7.0
  gotrue: ^2.1.0
  realtime_client: ^2.0.0
  hooks_riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  video_player: ^2.8.0
  network_info_plus: ^5.0.1  # For getting IP address
  device_info_plus: ^9.0.3   # For getting device info for user agent
  connectivity_plus: ^5.0.1
  package_info_plus: ^8.0.0
  flutter_secure_storage: ^9.0.0




  flutter_hooks: ^0.20.3
  timeago: ^3.4.1



  
  path: ^1.9.0
  path_provider: ^2.1.4
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.3.5
  intl: ^0.18.0
  http: ^1.2.0
  flutterwave_standard: ^1.0.6 
  uuid: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  fluttertoast: ^8.2.8 
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0 
  postgrest: ^2.3.0 

  cached_network_image: ^3.3.0 
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.3.2
  share_plus: ^7.0.1 
  gal: ^2.0.1
  app_links: ^3.4.1




  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0 
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/animations/
    - assets/logo.png



 

